#!/bin/bash
LINE_NUM=1
while read LINE
do 
	echo “${LINE_NUM}: ${LINE}”
	((LINE_NUM++))
done < /etc/passwd

# Same type of question is solved in Exercise done in the course. Exercise is available in Notes
